[PATHS]
iso = "~/Data/fax/Super Smash Bros. Melee (USA) (En,Ja) (v1.02).iso"
exe = "~/Data/fax/Slippi_Online-x86_64-ExiAI.AppImage"
slp = "~/Data/fax/ranked-anonymized/"
sql = "~/Data/fax/index.db"
mds = "~/Data/fax/mds/"
runs = "~/Data/fax/runs/"
logs = "~/Data/fax/logs/"
replays = "~/Data/fax/replays/"
dolphin-home = "~/.config/SlippiPlayback/"
[BASE]
seed = 42
debug = false
n-gpus = 1
[TRAINING]
batch-size = 64
n-epochs = 100
n-samples = 1000
n-eval-samples = 100
n-dataworkers = 4
[MODEL]
n-layers = 4
n-heads = 8
seq-len = 256
emb-dim = 256
dropout = 0.1
gamma = 0.999
[OPTIM]
lr = 3e-4
wd = 1e-2
b1 = 0.9
b2 = 0.999
