[project]
name = "fax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "91252200+Josef-Hlink@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jax[cuda12]>=0.6.0",
    "melee",
    "ruff>=0.11.8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
melee = { git = "https://github.com/vladfi1/libmelee.git", rev = "dev" }
